name: Wakatime Readme

permissions:
  contents: write

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: mmaachado/wakatime-readme@v1
        with:
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          
          ### content
          # SHOW_TITLE: false # optional
          # SECTION_NAME: waka # optional
          # BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # optional
          # CODE_LANG: markdown # optional
          # TIME_RANGE: last_7_days # optional
          # LANG_COUNT: 5 # optional
          # SHOW_TIME: true # optional
          # SHOW_TOTAL: true # optional
          # SHOW_MASKED_TIME: false # optional
          # STOP_AT_OTHER: false # optional
          # IGNORED_LANGUAGES: Binary YAML JSON TOML # optional
